'use client';
import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,ArrowRight,Check,ChevronLeft,CircleX,Info,Layers3,RotateCcw,ShoppingBag,Sparkles,Tag,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Progress} from '@/components/ui/progress';

type Theme='community'|'resale'|'vip'; type Focus='primary'|'error'|'trend'|'disabled'|'background';
declare global{interface Document{modelContext?:{registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options?:{signal:AbortSignal})=>void|Promise<void>}}}
type Question={focus:Focus;eyebrow:string;title:string;prompt:string;options:{label:string;code:string;detail:string}[];answer:number;lesson:string};
const themes:{id:Theme;name:string;note:string;color:string}[]=[
 {id:'community',name:'千岛社区',note:'主色映射为紫色',color:'#7C66FF'},
 {id:'resale',name:'千岛二手',note:'主色映射为红色',color:'#F96464'},
 {id:'vip',name:'奇货 VIP',note:'主色映射为金色',color:'#B98532'}];
const questions:Question[]=[
 {focus:'primary',eyebrow:'场景 01 · 主操作',title:'确认订单按钮应该标什么？',prompt:'三个产品的按钮长得不一样，但都承担页面最重要的提交动作。请选择设计稿交付给研发的正确标注。',options:[{label:'写死色值',code:'#7C66FF',detail:'复制当前页面看到的紫色'},{label:'基础色阶',code:'PrimaryPurple_05',detail:'直接引用紫色原料'},{label:'组件 Token',code:'button_primary.bg',detail:'再映射到 color_primary'}],answer:2,lesson:'按钮先描述“组件 × 状态 × 部位”，再由 color_primary 接入不同产品主题。换肤时不需要逐页修改。'},
 {focus:'background',eyebrow:'场景 02 · 浅色容器',title:'品牌浅背景从哪里来？',prompt:'页面顶部的活动卡片需要带一点品牌倾向，同时保持轻量。哪条映射能让它跟随主题切换？',options:[{label:'页面私有色',code:'campaign_bg_2026',detail:'为这张卡片新建一个 HEX'},{label:'语义映射',code:'bg_primary → color_primary − 4',detail:'使用主色的浅阶'},{label:'固定紫色',code:'PrimaryPurple_01',detail:'所有产品都用同一浅紫'}],answer:1,lesson:'“−4”表示沿色阶移动到更浅的阶位，不是 HEX 减 4，也不是简单降低 40% 透明度。'},
 {focus:'error',eyebrow:'场景 03 · 系统反馈',title:'删除失败提示如何配色？',prompt:'提示条包含图标、文字、边框和背景。它们是否应该全部使用同一个红色色值？',options:[{label:'全部同色',code:'Red_05',detail:'前景与背景完全一致'},{label:'品牌优先',code:'color_primary',detail:'强提醒都使用品牌色'},{label:'组件分部位',code:'alert_error.*',detail:'前景 error + 1，背景 error − 4'}],answer:2,lesson:'错误语义保持稳定，但组件内部不同部位需要不同阶位，才能建立层次并保证信息可读。'},
 {focus:'trend',eyebrow:'场景 04 · 业务语义',title:'价格上涨的红，等于错误红吗？',prompt:'“求购价上涨 +¥3”当前恰好与错误提示使用同一个红色。应该直接复用 color_error 吗？',options:[{label:'复用错误色',code:'color_error',detail:'视觉一样就共用'},{label:'业务语义色',code:'price_up → Red_x',detail:'含义独立，结果可暂时相同'},{label:'直接写色值',code:'#F96464',detail:'业务色无需进入 Token'}],answer:1,lesson:'相同 HEX 不代表相同语义。未来错误态与涨跌色可能分别调整，错误共用会造成不合理联动。'},
 {focus:'disabled',eyebrow:'场景 05 · 组件状态',title:'不可点击选项怎么标？',prompt:'这个复选框进入 disabled 状态。设计稿只写“灰色”够不够？',options:[{label:'够了',code:'color_gray',detail:'研发自己找相近灰色'},{label:'写透明度',code:'opacity: 40%',detail:'整体降低透明度'},{label:'状态 Token',code:'checkbox_disabled.*',detail:'分别定义边框、背景、图标'}],answer:2,lesson:'disabled 是组件状态，不是一种颜色。边框、背景和图标可能来自不同的语义映射。'},
 {focus:'primary',eyebrow:'场景 06 · 跨产品',title:'换成千岛二手后，谁应该变？',prompt:'主按钮从紫色变为红色。最小且正确的研发改动是什么？',options:[{label:'逐页替换',code:'Find #7C66FF → #F96464',detail:'设计稿与代码全部搜索替换'},{label:'修改主题映射',code:'theme.color_primary = Red_05',detail:'组件引用关系保持不变'},{label:'修改按钮组件',code:'button_primary = Red_05',detail:'组件内部判断产品'}],answer:1,lesson:'稳定的是组件与语义关系；变化的是产品主题到基础色阶的映射。'},
 {focus:'background',eyebrow:'场景 07 · 算法校色',title:'浅色阶偏脏，该在哪里改？',prompt:'设计师发现 Yellow_02 在白底上偏脏。怎样兼顾算法效率和视觉质量？',options:[{label:'当前页微调',code:'#FFF4B8',detail:'看起来舒服即可'},{label:'禁用算法',code:'全部凭感觉手调',detail:'每个页面重新选色'},{label:'统一人工校正',code:'校正基础色阶 → 回归验证',detail:'记录场景并验证影响面'}],answer:2,lesson:'算法负责批量生成，设计师负责感知校正；校正结果必须回到统一基础色板。'},
 {focus:'primary',eyebrow:'场景 08 · 最终心智',title:'设计师选色的正确顺序是？',prompt:'面对一个新页面元素，哪条路径能同时服务设计表达与研发实现？',options:[{label:'先看视觉',code:'挑 HEX → 找近似 Token',detail:'最后再解释用途'},{label:'先看页面',code:'复制邻近元素 → 微调',detail:'只保持当前页面协调'},{label:'先定含义',code:'语义 → 组件/状态/部位 → 主题 → 色阶',detail:'最终才得到 HEX'}],answer:2,lesson:'颜色是映射结果，不是思考起点。先确定“为什么用”，再确定组件、状态与部位。'}];
const paths:Record<Focus,string[]>={primary:['button_primary.bg','color_primary','theme.primary','Purple / Red / Gold 05'],error:['alert_error.text','color_error + 1','Red_06','#E94B4B'],trend:['price_up.text','price_up','Red_05','#F96464'],disabled:['checkbox_disabled.border','border_secondary','Neutral_02','rgba(0,0,0,.12)'],background:['campaign_surface.bg','bg_primary','color_primary − 4','Theme_01']};

function Preview({theme,focus}:{theme:Theme;focus:Focus}){return <div className={`phone theme-${theme}`}>
 <div className="phone-status"><b>9:41</b><span>● ● ▰</span></div><header className="app-header"><button aria-label="返回"><ChevronLeft/></button><strong>确认订单</strong><button aria-label="关闭"><X/></button></header>
 <main className="app-body"><section className={`campaign ${focus==='background'?'is-focus':''}`}><i><Sparkles/></i><div><small>岛民专享</small><b>本单预计可省 ¥18</b></div><ArrowRight/></section>
 <section className="product-card"><i><ShoppingBag/></i><div><b>DIMOO 云端漫游系列</b><span>全新未拆 · 正版现货</span><strong>¥ 128</strong></div></section>
 <section className={`trend ${focus==='trend'?'is-focus':''}`}><span>近 7 日求购价</span><b>上涨 +¥3</b></section>
 <section className={`error ${focus==='error'?'is-focus':''}`}><CircleX/><div><b>优惠券使用失败</b><span>该优惠券不适用于当前商品</span></div></section>
 <section className="options"><b>确认订单信息</b><label className={focus==='disabled'?'is-focus':''}><i className="check disabled"><Check/></i><span><b>使用余额抵扣</b><small>当前订单暂不可用</small></span></label><label><i className="check checked"><Check/></i><span><b>我已阅读交易须知</b><small>确认商品及收货信息无误</small></span></label></section></main>
 <footer className={`checkout ${focus==='primary'?'is-focus':''}`}><div><small>合计</small><b>¥128</b></div><button>确认并支付</button></footer></div>}

export default function Home(){const[theme,setTheme]=useState<Theme>('community');const[index,setIndex]=useState(0);const[answers,setAnswers]=useState<(number|null)[]>(Array(questions.length).fill(null));const[selected,setSelected]=useState<number|null>(null);const[submitted,setSubmitted]=useState(false);const score=useMemo(()=>answers.reduce<number>((s,a,i)=>s+(a===questions[i].answer?1:0),0),[answers]);
 useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const life=new AbortController();void Promise.resolve(context.registerTool({name:'set_color_theme',title:'切换产品主题',description:'切换测试页面当前展示的产品主题，用于比较同一组件在不同主题下的映射结果。',inputSchema:{type:'object',properties:{theme:{type:'string',enum:['community','resale','vip']}},required:['theme'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const value=(input as {theme?:string})?.theme;if(value!=='community'&&value!=='resale'&&value!=='vip')throw new Error('theme 必须是 community、resale 或 vip');setTheme(value);return{theme:value,status:'applied'}}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[]);
 if(index===questions.length){const percent=Math.round(score/questions.length*100);return <main className="result-page"><div className="result-card"><i><Layers3/></i><p>色彩映射测试完成</p><h1>{percent}<small> 分</small></h1><h2>{percent>=88?'你已经建立了 Token 心智':percent>=63?'方向正确，还需理清映射层级':'先别急着挑颜色，先确定它的含义'}</h2><p>你答对了 {score} / {questions.length} 题。跨页面一致不是让所有页面使用同一个 HEX，而是让相同含义遵守同一条映射规则。</p><div className="result-flow"><span>页面元素</span>→<span>组件 Token</span>→<span>语义 Token</span>→<span>产品主题</span>→<span>基础色阶</span></div><Button onClick={()=>{setIndex(0);setAnswers(Array(questions.length).fill(null));setSelected(null);setSubmitted(false)}}><RotateCcw/>重新测试</Button></div></main>}
 const q=questions[index],themeInfo=themes.find(t=>t.id===theme)!;const submit=()=>{if(selected===null)return;const next=[...answers];next[index]=selected;setAnswers(next);setSubmitted(true)};const next=()=>{setIndex(index+1);setSelected(null);setSubmitted(false)};
 return <main className="workbench"><header className="topbar"><div className="brand"><i><Layers3/></i><span><b>色彩映射实验室</b><small>产品设计团队 · 视觉化测试</small></span></div><div className="progress"><span>进度 {index+1} / {questions.length}</span><Progress value={(index+1)/questions.length*100}/></div><div className="score">当前得分 <b>{score}</b></div></header>
 <section className="workspace"><aside className="quiz"><div className="question-head"><span>{q.eyebrow}</span><em>{index+1}</em></div><h1>{q.title}</h1><p className="prompt">{q.prompt}</p><div className="answers" role="radiogroup" aria-label="选择答案">{q.options.map((o,i)=>{const state=submitted?(i===q.answer?'correct':i===selected?'wrong':''):(i===selected?'selected':'');return <button key={o.code} role="radio" aria-checked={selected===i} disabled={submitted} className={`answer ${state}`} onClick={()=>setSelected(i)}><i>{submitted&&i===q.answer?<Check/>:submitted&&i===selected?<X/>:String.fromCharCode(65+i)}</i><span><b>{o.label}</b><code>{o.code}</code><small>{o.detail}</small></span></button>})}</div>
 {submitted?<div className={`feedback ${selected===q.answer?'good':'bad'}`}><b>{selected===q.answer?<Check/>:<AlertTriangle/>}{selected===q.answer?'判断正确':'再理一遍映射关系'}</b><p>{q.lesson}</p></div>:<div className="hint"><Info/>选择后会显示映射原理</div>}<div className="actions"><Button disabled={selected===null} onClick={submitted?next:submit}>{submitted?(index===questions.length-1?'查看结果':'下一题'):'确认答案'}{submitted&&<ArrowRight/>}</Button></div></aside>
 <section className="preview"><div className="preview-head"><div><span>实时页面</span><b>{themeInfo.name} · 订单确认</b></div><em><i/>映射已同步</em></div><div className="theme-switch">{themes.map(t=><button key={t.id} className={theme===t.id?'active':''} onClick={()=>setTheme(t.id)}><i style={{background:t.color}}/><span><b>{t.name}</b><small>{t.note}</small></span></button>)}</div><div className="phone-stage"><Preview theme={theme} focus={q.focus}/></div></section>
 <aside className="inspector"><div className="inspector-head"><span>研发映射检查器</span><b>{q.focus==='trend'?'价格上涨文字':q.focus==='error'?'错误提示条':q.focus==='disabled'?'禁用复选框':q.focus==='background'?'品牌浅背景':'主操作按钮'}</b></div><div className="token-chain">{paths[q.focus].map((p,i)=><div className="token" key={p}><i>{i+1}</i><span><small>{['组件层','语义层','主题映射','基础色 / 输出'][i]}</small><code>{p}</code></span>{i<3&&<ArrowRight/>}</div>)}</div><div className="swatch"><i style={{background:q.focus==='error'||q.focus==='trend'?'#F96464':q.focus==='disabled'?'#dddbe2':themeInfo.color}}/><span><small>当前渲染结果</small><b>{themeInfo.name}</b><code>{q.focus==='error'||q.focus==='trend'?'#F96464':q.focus==='disabled'?'Neutral_02':themeInfo.color}</code></span></div><div className="principle"><Tag/><p><b>这一题要理解</b><span>{q.focus==='trend'?'视觉相同，不代表语义相同。':q.focus==='error'?'同一语义，不同部位使用不同阶位。':q.focus==='disabled'?'状态不是颜色，需要完整映射。':q.focus==='background'?'相对色阶让浅背景跟随主题。':'组件不关心最终是紫、红还是金。'}</span></p></div></aside></section></main>}
