'use client';
export const dynamic = 'force-static';
import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,ArrowRight,Check,ChevronLeft,CircleX,Info,Layers3,RotateCcw,ShoppingBag,Sparkles,Tag,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Progress} from '@/components/ui/progress';

type Theme='qiandao'|'qihuo'|'linjie'|'mihua'; type Focus='primary'|'error'|'trend'|'disabled'|'background';
declare global{interface Document{modelContext?:{registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options?:{signal:AbortSignal})=>void|Promise<void>}}}
type Question={focus:Focus;eyebrow:string;title:string;prompt:string;options:{label:string;code:string;detail:string}[];answer:number;lesson:string};
const themes:{id:Theme;name:string;note:string;color:string;soft:string}[]=[
 {id:'qiandao',name:'千岛',note:'primary.5 · 紫色',color:'#7C66FF',soft:'#F2F0FF'},
 {id:'qihuo',name:'奇货',note:'primary.5 · 橙色',color:'#FC7E22',soft:'#FFF0E6'},
 {id:'linjie',name:'临界',note:'primary.5 · 紫色',color:'#7247DC',soft:'#7247DC'},
 {id:'mihua',name:'米花',note:'primary.5 · 黄绿色',color:'#AEF056',soft:'#E9FCD0'}];
const questions:Question[]=[
 {focus:'primary',eyebrow:'场景 01 · 主操作',title:'确认订单按钮应该标什么？',prompt:'三个产品的按钮长得不一样，但都承担页面最重要的提交动作。请选择设计稿交付给研发的正确标注。',options:[{label:'写死色值',code:'#7C66FF',detail:'复制当前页面看到的紫色'},{label:'基础色阶',code:'PrimaryPurple_05',detail:'直接引用紫色原料'},{label:'组件 Token',code:'button_primary.bg',detail:'再映射到 color_primary'}],answer:2,lesson:'按钮先描述“组件 × 状态 × 部位”，再由 color_primary 接入不同产品主题。换肤时不需要逐页修改。'},
 {focus:'background',eyebrow:'场景 02 · 浅色容器',title:'品牌浅背景从哪里来？',prompt:'页面顶部的活动卡片需要带一点品牌倾向，同时保持轻量。哪条映射符合实际项目 Token，并能跟随主题切换？',options:[{label:'页面私有色',code:'campaign_bg_2026',detail:'为这张卡片新建一个 HEX'},{label:'语义映射',code:'primary.softBg → primary.1 / 临界 primary.3',detail:'由各 App 的真实语义 Token 决定'},{label:'固定紫色',code:'PrimaryPurple_01',detail:'所有产品都用同一浅紫'}],answer:1,lesson:'实际文件使用 primary.softBg：千岛、奇货、米花引用 primary.1；临界引用 primary.3。设计稿应标语义 Token，不应再沿用旧表中的“color_primary − 4”。'},
 {focus:'error',eyebrow:'场景 03 · 系统反馈',title:'删除失败提示如何配色？',prompt:'提示条包含图标、文字、边框和背景。它们是否应该全部使用同一个红色色值？',options:[{label:'全部同色',code:'Red_05',detail:'前景与背景完全一致'},{label:'品牌优先',code:'color_primary',detail:'强提醒都使用品牌色'},{label:'组件分部位',code:'alert_error.*',detail:'前景 error + 1，背景 error − 4'}],answer:2,lesson:'错误语义保持稳定，但组件内部不同部位需要不同阶位，才能建立层次并保证信息可读。'},
 {focus:'trend',eyebrow:'场景 04 · 业务语义',title:'价格上涨的红，等于错误红吗？',prompt:'“求购价上涨 +¥3”当前恰好与错误提示使用同一个红色。应该直接复用 color_error 吗？',options:[{label:'复用错误色',code:'color_error',detail:'视觉一样就共用'},{label:'业务语义色',code:'price_up → Red_x',detail:'含义独立，结果可暂时相同'},{label:'直接写色值',code:'#F96464',detail:'业务色无需进入 Token'}],answer:1,lesson:'相同 HEX 不代表相同语义。未来错误态与涨跌色可能分别调整，错误共用会造成不合理联动。'},
 {focus:'disabled',eyebrow:'场景 05 · 组件状态',title:'不可点击选项怎么标？',prompt:'这个复选框进入 disabled 状态。设计稿只写“灰色”够不够？',options:[{label:'够了',code:'color_gray',detail:'研发自己找相近灰色'},{label:'写透明度',code:'opacity: 40%',detail:'整体降低透明度'},{label:'状态 Token',code:'checkbox_disabled.*',detail:'分别定义边框、背景、图标'}],answer:2,lesson:'disabled 是组件状态，不是一种颜色。边框、背景和图标可能来自不同的语义映射。'},
 {focus:'primary',eyebrow:'场景 06 · 跨产品',title:'换成奇货后，谁应该变？',prompt:'主按钮从千岛紫 #7C66FF 变为奇货橙 #FC7E22。最小且正确的研发改动是什么？',options:[{label:'逐页替换',code:'Find #7C66FF → #FC7E22',detail:'设计稿与代码全部搜索替换'},{label:'修改主题映射',code:'qihuo.primary.5 = #FC7E22',detail:'组件引用关系保持不变'},{label:'修改按钮组件',code:'button_primary = Orange_05',detail:'组件内部判断产品'}],answer:1,lesson:'稳定的是组件与语义关系；变化的是产品主题到基础色阶的映射。'},
 {focus:'background',eyebrow:'场景 07 · 算法校色',title:'浅色阶偏脏，该在哪里改？',prompt:'设计师发现 Yellow_02 在白底上偏脏。怎样兼顾算法效率和视觉质量？',options:[{label:'当前页微调',code:'#FFF4B8',detail:'看起来舒服即可'},{label:'禁用算法',code:'全部凭感觉手调',detail:'每个页面重新选色'},{label:'统一人工校正',code:'校正基础色阶 → 回归验证',detail:'记录场景并验证影响面'}],answer:2,lesson:'算法负责批量生成，设计师负责感知校正；校正结果必须回到统一基础色板。'},
 {focus:'primary',eyebrow:'场景 08 · 跨 App 跳转',title:'从千岛进入奇货下单页，主题跟谁走？',prompt:'用户从千岛内容页点击商品，进入奇货的独立下单流程。下单页主按钮应该使用哪个主题？',options:[{label:'跟随来源页',code:'qiandao.primary.5',detail:'用户是从千岛点击进来的'},{label:'跟随目标业务',code:'qihuo.primary.5',detail:'下单页由奇货 App 负责'},{label:'随机继承',code:'previous_page.primary',detail:'保留上一个页面的 CSS 变量'}],answer:1,lesson:'进入边界明确的目标业务 App 后，业务页面使用目标 App 主题。来源只解释导航路径，不应该污染目标页面的主题契约。'},
 {focus:'error',eyebrow:'场景 09 · 共享组件',title:'跨 App 后，错误提示要跟着换主色吗？',prompt:'同一个支付失败提示同时出现在千岛、奇货、临界与米花。四套文件的 error.5 都是 #F96464，应该如何处理？',options:[{label:'全部改用各自主色',code:'toast_error → primary.5',detail:'让提示更有品牌感'},{label:'复用错误语义',code:'toast_error → error.5',detail:'四套主题当前映射结果一致'},{label:'每页单独设计',code:'page.toast.hex',detail:'按页面视觉平衡决定'}],answer:1,lesson:'真实 Token 证明共享错误语义可以跨主题保持一致。品牌换肤不等于把所有强调色都换成主色。'},
 {focus:'primary',eyebrow:'场景 10 · 壳层与内容',title:'顶部导航和业务按钮必须同色吗？',prompt:'页面仍在千岛全局壳层内，但内容区嵌入了临界业务模块。顶部导航与模块主按钮该如何取主题？',options:[{label:'必须统一',code:'shell.primary = module.primary',detail:'一个屏幕只能有一个主题'},{label:'分层归属',code:'shell theme + module theme',detail:'壳层与业务模块各自负责'},{label:'全部跟模块',code:'page.theme = critical',detail:'出现模块就整页换肤'}],answer:1,lesson:'先判断主题作用域。全局壳层与独立业务模块可以拥有不同主题，但边界必须明确，避免同一组件被双重主题控制。'},
 {focus:'background',eyebrow:'场景 11 · 页面归属',title:'聚合页展示多个 App 卡片，背景怎么用？',prompt:'首页同时展示千岛、奇货、临界、米花入口卡片。整个页面的大背景应该取哪个 App 的主色浅阶？',options:[{label:'取第一个卡片',code:'bg = first_card.primary.1',detail:'按内容排序自动变化'},{label:'使用壳层背景',code:'page.bg → shell.bg',detail:'卡片内部再表达各自主题'},{label:'四色混合',code:'mix(all_app_primary)',detail:'让每个 App 都被照顾到'}],answer:1,lesson:'聚合页属于全局壳层，页面级背景使用壳层语义；各 App 的主题色应限制在各自入口或模块边界内。'},
 {focus:'background',eyebrow:'场景 12 · 色阶完整性',title:'临界的浅背景可以直接用 primary.1 吗？',prompt:'实际文件中临界 primary.1～9 当前都导出为 #7247DC，而其他主题的 primary.1 是浅色。组件需要浅色背景时应该怎么办？',options:[{label:'照常使用',code:'linjie.primary.1',detail:'只要名字叫 1 就一定是浅色'},{label:'改成透明度',code:'#7247DC / 10%',detail:'设计师单页临时处理'},{label:'标记映射缺口',code:'softBg 待主题 Owner 校验',detail:'不假设阶位具有相同视觉作用'}],answer:2,lesson:'Token 名称不能替代实际值验证。跨主题映射必须检查每套主题是否真的提供等价视觉角色，缺失时进入治理，而不是页面私改。'},
 {focus:'primary',eyebrow:'场景 13 · 最终心智',title:'设计师选色的正确顺序是？',prompt:'面对一个新页面元素，哪条路径能同时服务设计表达与研发实现？',options:[{label:'先看视觉',code:'挑 HEX → 找近似 Token',detail:'最后再解释用途'},{label:'先看页面',code:'复制邻近元素 → 微调',detail:'只保持当前页面协调'},{label:'先定归属与含义',code:'App/作用域 → 语义 → 组件/状态 → 色阶',detail:'最终才得到 HEX'}],answer:2,lesson:'颜色是映射结果，不是思考起点。跨 App 时先确定页面和组件属于谁，再判断语义、状态与部位。'}];
const paths:Record<Focus,string[]>={primary:['button_primary.bg','primary.solidBg','当前 App 主题','primary.5 / 临界 primary.9'],error:['alert_error.text','error.color','四套主题一致','error.5 · #F96464'],trend:['price_up.text','trade.color','当前 App 主题','trade.5'],disabled:['checkbox_disabled.border','border.2 / icon.disabled','当前 App 主题','实际 Primitive'],background:['campaign_surface.bg','primary.softBg','当前 App 主题','primary.1 / 临界 primary.3']};

function Preview({theme,focus}:{theme:Theme;focus:Focus}){return <div className={`phone theme-${theme}`}>
 <div className="phone-status"><b>9:41</b><span>● ● ▰</span></div><header className="app-header"><button aria-label="返回"><ChevronLeft/></button><strong>确认订单</strong><button aria-label="关闭"><X/></button></header>
 <main className="app-body"><section className={`campaign ${focus==='background'?'is-focus':''}`}><i><Sparkles/></i><div><small>岛民专享</small><b>本单预计可省 ¥18</b></div><ArrowRight/></section>
 <section className="product-card"><i><ShoppingBag/></i><div><b>DIMOO 云端漫游系列</b><span>全新未拆 · 正版现货</span><strong>¥ 128</strong></div></section>
 <section className={`trend ${focus==='trend'?'is-focus':''}`}><span>近 7 日求购价</span><b>上涨 +¥3</b></section>
 <section className={`error ${focus==='error'?'is-focus':''}`}><CircleX/><div><b>优惠券使用失败</b><span>该优惠券不适用于当前商品</span></div></section>
 <section className="options"><b>确认订单信息</b><label className={focus==='disabled'?'is-focus':''}><i className="check disabled"><Check/></i><span><b>使用余额抵扣</b><small>当前订单暂不可用</small></span></label><label><i className="check checked"><Check/></i><span><b>我已阅读交易须知</b><small>确认商品及收货信息无误</small></span></label></section></main>
 <footer className={`checkout ${focus==='primary'?'is-focus':''}`}><div><small>合计</small><b>¥128</b></div><button>确认并支付</button></footer></div>}

export default function Home(){const[theme,setTheme]=useState<Theme>('qiandao');const[index,setIndex]=useState(0);const[answers,setAnswers]=useState<(number|null)[]>(Array(questions.length).fill(null));const[selected,setSelected]=useState<number|null>(null);const[submitted,setSubmitted]=useState(false);const score=useMemo(()=>answers.reduce<number>((s,a,i)=>s+(a===questions[i].answer?1:0),0),[answers]);
 useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const life=new AbortController();void Promise.resolve(context.registerTool({name:'set_color_theme',title:'切换产品主题',description:'切换测试页面当前展示的产品主题，用于比较同一组件在不同主题下的映射结果。',inputSchema:{type:'object',properties:{theme:{type:'string',enum:['qiandao','qihuo','linjie','mihua']}},required:['theme'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const value=(input as {theme?:string})?.theme;if(value!=='qiandao'&&value!=='qihuo'&&value!=='linjie'&&value!=='mihua')throw new Error('theme 必须是 qiandao、qihuo、linjie 或 mihua');setTheme(value);return{theme:value,status:'applied'}}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[]);
 if(index===questions.length){const percent=Math.round(score/questions.length*100);return <main className="result-page"><div className="result-card"><i><Layers3/></i><p>色彩映射测试完成</p><h1>{percent}<small> 分</small></h1><h2>{percent>=88?'你已经建立了 Token 心智':percent>=63?'方向正确，还需理清映射层级':'先别急着挑颜色，先确定它的含义'}</h2><p>你答对了 {score} / {questions.length} 题。跨页面一致不是让所有页面使用同一个 HEX，而是让相同含义遵守同一条映射规则。</p><blockquote className="result-quote">“颜色不是页面的装饰，而是系统对含义的承诺。页面会变，主题会换，只有语义应该稳定。”</blockquote><div className="result-flow"><span>页面元素</span>→<span>组件 Token</span>→<span>语义 Token</span>→<span>产品主题</span>→<span>基础色阶</span></div><Button onClick={()=>{setIndex(0);setAnswers(Array(questions.length).fill(null));setSelected(null);setSubmitted(false)}}><RotateCcw/>重新测试</Button></div></main>}
 const q=questions[index],themeInfo=themes.find(t=>t.id===theme)??themes[0];const submit=()=>{if(selected===null)return;const next=[...answers];next[index]=selected;setAnswers(next);setSubmitted(true)};const next=()=>{setIndex(index+1);setSelected(null);setSubmitted(false)};
 return <main className="workbench"><header className="topbar"><div className="brand"><i><Layers3/></i><span><b>色彩映射实验室</b><small>产品设计团队 · 视觉化测试</small></span></div><div className="progress"><span>进度 {index+1} / {questions.length}</span><Progress value={(index+1)/questions.length*100}/></div><div className="score">当前得分 <b>{score}</b></div></header>
 <section className="workspace"><aside className="quiz"><div className="question-head"><span>{q.eyebrow}</span><em>{index+1}</em></div><h1>{q.title}</h1><p className="prompt">{q.prompt}</p><div className="answers" role="radiogroup" aria-label="选择答案">{q.options.map((o,i)=>{const state=submitted?(i===q.answer?'correct':i===selected?'wrong':''):(i===selected?'selected':'');return <button key={o.code} role="radio" aria-checked={selected===i} disabled={submitted} className={`answer ${state}`} onClick={()=>setSelected(i)}><i>{submitted&&i===q.answer?<Check/>:submitted&&i===selected?<X/>:String.fromCharCode(65+i)}</i><span><b>{o.label}</b><code>{o.code}</code><small>{o.detail}</small></span></button>})}</div>
 {submitted?<div className={`feedback ${selected===q.answer?'good':'bad'}`}><b>{selected===q.answer?<Check/>:<AlertTriangle/>}{selected===q.answer?'判断正确':'再理一遍映射关系'}</b><p>{q.lesson}</p></div>:<div className="hint"><Info/>选择后会显示映射原理</div>}<div className="actions"><Button disabled={selected===null} onClick={submitted?next:submit}>{submitted?(index===questions.length-1?'查看结果':'下一题'):'确认答案'}{submitted&&<ArrowRight/>}</Button></div></aside>
 <section className="preview"><div className="preview-head"><div><span>实时页面</span><b>{themeInfo.name} · 订单确认</b></div><em><i/>映射已同步</em></div><div className="theme-switch">{themes.map(t=><button key={t.id} className={theme===t.id?'active':''} onClick={()=>setTheme(t.id)}><i style={{background:t.color}}/><span><b>{t.name}</b><small>{t.note}</small></span></button>)}</div><div className="phone-stage"><Preview theme={theme} focus={q.focus}/></div></section>
 <aside className="inspector"><div className="inspector-head"><span>研发映射检查器</span><b>{q.focus==='trend'?'价格上涨文字':q.focus==='error'?'错误提示条':q.focus==='disabled'?'禁用复选框':q.focus==='background'?'品牌浅背景':'主操作按钮'}</b></div><div className="token-chain">{paths[q.focus].map((p,i)=><div className="token" key={p}><i>{i+1}</i><span><small>{['组件层','语义层','主题映射','基础色 / 输出'][i]}</small><code>{p}</code></span>{i<3&&<ArrowRight/>}</div>)}</div><div className="swatch"><i style={{background:q.focus==='error'||q.focus==='trend'?'#F96464':q.focus==='disabled'?'#D4D0DA':q.focus==='background'?themeInfo.soft:themeInfo.color}}/><span><small>当前渲染结果</small><b>{themeInfo.name}</b><code>{q.focus==='error'||q.focus==='trend'?'#F96464':q.focus==='disabled'?'icon.disabled':q.focus==='background'?themeInfo.soft:themeInfo.color}</code></span></div><div className="principle"><Tag/><p><b>这一题要理解</b><span>{q.focus==='trend'?'视觉相同，不代表语义相同。':q.focus==='error'?'四套主题的错误语义当前都映射为 #F96464。':q.focus==='disabled'?'状态不是颜色，需要完整映射。':q.focus==='background'?'同名色阶也必须验证实际视觉作用。':'组件不关心最终是紫、橙、深紫还是黄绿。'}</span></p></div></aside></section></main>}
